# Note: If providing a full Windows path, use single quotes (e.g., 'C:\path\to\file.pdf') or forward slashes (C:/path/to/file.pdf)
nagios_report: "report.pdf"

credentials:
  # Global credentials used by all handlers. Leave empty to prompt in terminal.
  username: ""
  password: ""

rules:
  # Example of using regex for host matching
  # - name: "FortiGate Custom Regex"
  #   host_filter:
  #     regex: "^(FGTDEMO|SWDEMO)"
  #   handler: "fortigate"
  #   options: {}
  
  - name: "FortiGate"
    host_filter:
      startswith: "FGT"
    handler: "fortigate"
    options:
      url_template: "https://{host}/ng/interface"
      # You can override credentials here for this specific rule if needed
      # username: "specific_admin"
      # password: ""

  - name: "Switch"
    host_filter:
      startswith: "SW" # Match switches or servers
    handler: "generic_ping"
    options: {}

  - name: "Access Point"
    host_filter:
      startswith: "AP" # Match switches or servers
    handler: "generic_ping"
    options: {}

exporters:
  - type: "docx"
    language: ["pt-BR", "en"] # Will generate one report per language
    output_file: "Evidence_Report.docx"
