# Note: If providing a full Windows path, use single quotes (e.g., 'C:\path\to\file.pdf') or forward slashes (C:/path/to/file.pdf)
nagios_report: "report.pdf"

credentials:
  # Global credentials used by all handlers. Leave empty to prompt in terminal.
  username: ""
  password: ""

rules:
  # Example of using regex for host matching
  # - name: "FortiGate Custom Regex"
  #   host_filter:
  #     regex: "^(FGTDEMO|SWDEMO)"
  #   handler: "fortigate"
  #   options: {}

  # Example of using regex to EXCLUDE a specific host (Negative Lookahead)
  # - name: "All FortiGates EXCEPT FGTDEMO01"
  #   host_filter:
  #     regex: "^FGT(?!DEMO01$)"
  #   handler: "fortigate"
  #   options: {}
  
  - name: "FortiGate"
    host_filter:
      startswith: "FGT"
    handler: "fortigate"
    options:
      url_template: "https://{host}/ng/interface"
      gather_gateway: false # Set to true to scrape the routing table and expose the gateway IP to the Word template
      diagnose_interfaces:
        - "wan1"
        - "wan2"
        - "internal5|port5" # Use '|' to provide fallbacks for mixed hardware
      ping:
        "default": # Global defaults for all interfaces
          enabled: true # Ping is disabled by default
          target: "interface" # Set to "gateway" to ping the gateway, "interface" to ping the interface IP, or a custom IP like "8.8.8.8"
          method: "host" # Use "cli" to ping through the Fortigate CLI Console, or "host" to ping from this machine
        "wan1": # Override rules for specific interface
          target: "gateway"
      # You can override credentials here for this specific rule if needed
      # username: "specific_admin"
      # password: ""

  - name: "Switch"
    host_filter:
      startswith: "SW" # Match switches or servers
    handler: "generic_ping"
    options: {}

  - name: "Access Point"
    host_filter:
      startswith: "AP" # Match switches or servers
    handler: "generic_ping"
    options: {}

exporters:
  - type: "docx"
    language: ["pt-BR", "en"] # Will generate one report per language
    output_file: "Evidence_Report.docx"
