name: Build and Release Windows Binary
run-name: Release ${{ github.ref_name }}
on:
  push:
    tags:
      - '*' # Trigger on any tag push

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Inject Version
      run: |
        (Get-Content main.py) -replace 'VERSION = "DEV_BUILD"', "VERSION = `"${{ github.ref_name }}`"" | Set-Content main.py

    - name: Build executable
      run: |
        pyinstaller --onedir --name Nagios-Sust-x64 --hidden-import handlers.fortigate --hidden-import exporters.docx_exporter main.py

    - name: Prepare Release Package
      run: |
        mkdir release_package
        # Move the compiled directory structure into the release folder
        Move-Item -Path dist\Nagios-Sust-x64 -Destination release_package\
        # Copy configuration files inside the executable's directory
        copy config.example.yaml release_package\Nagios-Sust-x64\
        copy template_en.example.docx release_package\Nagios-Sust-x64\
        copy template_pt-BR.example.docx release_package\Nagios-Sust-x64\
        # Create final zip containing the folder contents directly
        Compress-Archive -Path release_package\Nagios-Sust-x64\* -DestinationPath Nagios-Sust-win-x64.zip

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: Nagios-Sust-win-x64.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
